version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.11"
   jobs:
      pre_create_environment:
         - sudo apt install -y protobuf-compiler
         - make python/gink/builders

sphinx:
   configuration: python/docs/conf.py

python:
   install:
   - run: pip install .
   - run: pip install 'gink[docs]'
