version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.11"
   apt_packages:
      - protobuf-compiler
   jobs:
      pre_create_environment:
         - make python/gink/builders
         - export VERSION=`date -u +0.%Y%m%d.%s` && sed -i "s/\${VERSION}/${VERSION}/g" setup.py

sphinx:
   configuration: python/docs/conf.py

python:
   install:
   - method: pip
     path: ./python
     extra_requirements:
      - docs
