FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing && apt-get upgrade -y
COPY packages.txt ./
RUN apt-get install -y `cat packages.txt | tr '\n' ' '`
RUN npm install -g protoc-gen-js
RUN curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
RUN chmod +x mkcert-v*-linux-amd64
RUN cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
RUN mkcert -install
RUN mkcert localhost
