export type Bytes = Uint8Array;
export type GreetingBytes = Bytes;
export type ChangeSetBytes = Bytes;
export type Medallion = number;
export type Timestamp = number;
export type ChainStart = Timestamp;
export type SeenThrough = Timestamp;
export type PriorTime = Timestamp;
export type ClaimedChains = Map<Medallion, ChainStart>;
export type Offset = number;
export type FilePath = string;
export type NumberStr = string;
export type Basic = number | string | boolean | null;  // TODO: add bigints, bytes
