# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='behavior.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x62\x65havior.proto\x12\x0bgoogle.gink*\xaf\x01\n\x08\x42\x65havior\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x42OX\x10\x01\x12\x08\n\x04\x46ILE\x10\x02\x12\n\n\x06STREAM\x10\x03\x12\x0e\n\nMEMBERSHIP\x10\x04\x12\x0b\n\x07KEY_SET\x10\x05\x12\x0c\n\x08PAIR_MAP\x10\x06\x12\r\n\tDIRECTORY\x10\x07\x12\x0c\n\x08SEQUENCE\x10\x08\x12\x0c\n\x08PROPERTY\x10\t\x12\x0c\n\x08REGISTRY\x10\x0b\x12\x0f\n\x0bPLACEHOLDER\x10\rb\x06proto3'
)

_BEHAVIOR = _descriptor.EnumDescriptor(
  name='Behavior',
  full_name='google.gink.Behavior',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOX', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STREAM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMBERSHIP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEY_SET', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAIR_MAP', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIRECTORY', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEQUENCE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROPERTY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REGISTRY', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLACEHOLDER', index=11, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=207,
)
_sym_db.RegisterEnumDescriptor(_BEHAVIOR)

Behavior = enum_type_wrapper.EnumTypeWrapper(_BEHAVIOR)
UNSPECIFIED = 0
BOX = 1
FILE = 2
STREAM = 3
MEMBERSHIP = 4
KEY_SET = 5
PAIR_MAP = 6
DIRECTORY = 7
SEQUENCE = 8
PROPERTY = 9
REGISTRY = 11
PLACEHOLDER = 13


DESCRIPTOR.enum_types_by_name['Behavior'] = _BEHAVIOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
