# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bundle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import change_pb2 as change__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bundle.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62undle.proto\x12\x0bgoogle.gink\x1a\x0c\x63hange.proto\"\xde\x01\n\x06\x42undle\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x11\n\tmedallion\x18\x02 \x01(\x04\x12\x10\n\x08previous\x18\x03 \x01(\x04\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x13\n\x0b\x63hain_start\x18\x05 \x01(\x04\x12\x31\n\x07\x63hanges\x18\x06 \x03(\x0b\x32 .google.gink.Bundle.ChangesEntry\x1a\x43\n\x0c\x43hangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.google.gink.Change:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[change__pb2.DESCRIPTOR,])




_BUNDLE_CHANGESENTRY = _descriptor.Descriptor(
  name='ChangesEntry',
  full_name='google.gink.Bundle.ChangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='google.gink.Bundle.ChangesEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='google.gink.Bundle.ChangesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=266,
)

_BUNDLE = _descriptor.Descriptor(
  name='Bundle',
  full_name='google.gink.Bundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='google.gink.Bundle.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medallion', full_name='google.gink.Bundle.medallion', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous', full_name='google.gink.Bundle.previous', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='google.gink.Bundle.comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_start', full_name='google.gink.Bundle.chain_start', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='changes', full_name='google.gink.Bundle.changes', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BUNDLE_CHANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=266,
)

_BUNDLE_CHANGESENTRY.fields_by_name['value'].message_type = change__pb2._CHANGE
_BUNDLE_CHANGESENTRY.containing_type = _BUNDLE
_BUNDLE.fields_by_name['changes'].message_type = _BUNDLE_CHANGESENTRY
DESCRIPTOR.message_types_by_name['Bundle'] = _BUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bundle = _reflection.GeneratedProtocolMessageType('Bundle', (_message.Message,), {

  'ChangesEntry' : _reflection.GeneratedProtocolMessageType('ChangesEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUNDLE_CHANGESENTRY,
    '__module__' : 'bundle_pb2'
    # @@protoc_insertion_point(class_scope:google.gink.Bundle.ChangesEntry)
    })
  ,
  'DESCRIPTOR' : _BUNDLE,
  '__module__' : 'bundle_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Bundle)
  })
_sym_db.RegisterMessage(Bundle)
_sym_db.RegisterMessage(Bundle.ChangesEntry)


_BUNDLE_CHANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
