# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: change.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import container_pb2 as container__pb2
from . import entry_pb2 as entry__pb2
from . import movement_pb2 as movement__pb2
from . import clearance_pb2 as clearance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='change.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63hange.proto\x12\x0bgoogle.gink\x1a\x0f\x63ontainer.proto\x1a\x0b\x65ntry.proto\x1a\x0emovement.proto\x1a\x0f\x63learance.proto\"\xb9\x01\n\x06\x43hange\x12+\n\tcontainer\x18\x01 \x01(\x0b\x32\x16.google.gink.ContainerH\x00\x12#\n\x05\x65ntry\x18\x02 \x01(\x0b\x32\x12.google.gink.EntryH\x00\x12)\n\x08movement\x18\x03 \x01(\x0b\x32\x15.google.gink.MovementH\x00\x12+\n\tclearance\x18\x04 \x01(\x0b\x32\x16.google.gink.ClearanceH\x00\x42\x05\n\x03objb\x06proto3'
  ,
  dependencies=[container__pb2.DESCRIPTOR,entry__pb2.DESCRIPTOR,movement__pb2.DESCRIPTOR,clearance__pb2.DESCRIPTOR,])




_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='google.gink.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='google.gink.Change.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entry', full_name='google.gink.Change.entry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movement', full_name='google.gink.Change.movement', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clearance', full_name='google.gink.Change.clearance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='obj', full_name='google.gink.Change.obj',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=93,
  serialized_end=278,
)

_CHANGE.fields_by_name['container'].message_type = container__pb2._CONTAINER
_CHANGE.fields_by_name['entry'].message_type = entry__pb2._ENTRY
_CHANGE.fields_by_name['movement'].message_type = movement__pb2._MOVEMENT
_CHANGE.fields_by_name['clearance'].message_type = clearance__pb2._CLEARANCE
_CHANGE.oneofs_by_name['obj'].fields.append(
  _CHANGE.fields_by_name['container'])
_CHANGE.fields_by_name['container'].containing_oneof = _CHANGE.oneofs_by_name['obj']
_CHANGE.oneofs_by_name['obj'].fields.append(
  _CHANGE.fields_by_name['entry'])
_CHANGE.fields_by_name['entry'].containing_oneof = _CHANGE.oneofs_by_name['obj']
_CHANGE.oneofs_by_name['obj'].fields.append(
  _CHANGE.fields_by_name['movement'])
_CHANGE.fields_by_name['movement'].containing_oneof = _CHANGE.oneofs_by_name['obj']
_CHANGE.oneofs_by_name['obj'].fields.append(
  _CHANGE.fields_by_name['clearance'])
_CHANGE.fields_by_name['clearance'].containing_oneof = _CHANGE.oneofs_by_name['obj']
DESCRIPTOR.message_types_by_name['Change'] = _CHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Change = _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), {
  'DESCRIPTOR' : _CHANGE,
  '__module__' : 'change_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Change)
  })
_sym_db.RegisterMessage(Change)


# @@protoc_insertion_point(module_scope)
