# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clearance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import muid_pb2 as muid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='clearance.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63learance.proto\x12\x0bgoogle.gink\x1a\nmuid.proto\"@\n\tClearance\x12$\n\tcontainer\x18\x01 \x01(\x0b\x32\x11.google.gink.Muid\x12\r\n\x05purge\x18\x02 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[muid__pb2.DESCRIPTOR,])




_CLEARANCE = _descriptor.Descriptor(
  name='Clearance',
  full_name='google.gink.Clearance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='google.gink.Clearance.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='purge', full_name='google.gink.Clearance.purge', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=108,
)

_CLEARANCE.fields_by_name['container'].message_type = muid__pb2._MUID
DESCRIPTOR.message_types_by_name['Clearance'] = _CLEARANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Clearance = _reflection.GeneratedProtocolMessageType('Clearance', (_message.Message,), {
  'DESCRIPTOR' : _CLEARANCE,
  '__module__' : 'clearance_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Clearance)
  })
_sym_db.RegisterMessage(Clearance)


# @@protoc_insertion_point(module_scope)
