# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import value_pb2 as value__pb2
from . import muid_pb2 as muid__pb2
from . import behavior_pb2 as behavior__pb2
from . import key_pb2 as key__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='entry.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65ntry.proto\x12\x0bgoogle.gink\x1a\x0bvalue.proto\x1a\nmuid.proto\x1a\x0e\x62\x65havior.proto\x1a\tkey.proto\"\x9a\x04\n\x05\x45ntry\x12$\n\tcontainer\x18\x01 \x01(\x0b\x32\x11.google.gink.Muid\x12\'\n\x08\x62\x65havior\x18\x02 \x01(\x0e\x32\x15.google.gink.Behavior\x12\x1f\n\x03key\x18\x03 \x01(\x0b\x32\x10.google.gink.KeyH\x00\x12\'\n\x04pair\x18\x04 \x01(\x0b\x32\x17.google.gink.Entry.PairH\x00\x12\'\n\x04span\x18\x05 \x01(\x0b\x32\x17.google.gink.Entry.SpanH\x00\x12\'\n\ndescribing\x18\x06 \x01(\x0b\x32\x11.google.gink.MuidH\x00\x12#\n\x05value\x18\x07 \x01(\x0b\x32\x12.google.gink.ValueH\x01\x12\x10\n\x06octets\x18\x08 \x01(\x0cH\x01\x12\x12\n\x08\x64\x65letion\x18\t \x01(\x08H\x01\x12$\n\x07pointee\x18\n \x01(\x0b\x32\x11.google.gink.MuidH\x01\x12\x0e\n\x06\x65xpiry\x18\x0b \x01(\x04\x12\x11\n\teffective\x18\x0c \x01(\x12\x12\r\n\x05purge\x18\r \x01(\x08\x1a\"\n\x04Span\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x04\x12\x0c\n\x04\x65nds\x18\x02 \x01(\x04\x1aH\n\x04Pair\x12\x1f\n\x04left\x18\x01 \x01(\x0b\x32\x11.google.gink.Muid\x12\x1f\n\x04rite\x18\x02 \x01(\x0b\x32\x11.google.gink.MuidB\t\n\x07subjectB\n\n\x08\x63ontainsb\x06proto3'
  ,
  dependencies=[value__pb2.DESCRIPTOR,muid__pb2.DESCRIPTOR,behavior__pb2.DESCRIPTOR,key__pb2.DESCRIPTOR,])




_ENTRY_SPAN = _descriptor.Descriptor(
  name='Span',
  full_name='google.gink.Entry.Span',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='google.gink.Entry.Span.from', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ends', full_name='google.gink.Entry.Span.ends', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=522,
)

_ENTRY_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='google.gink.Entry.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='google.gink.Entry.Pair.left', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rite', full_name='google.gink.Entry.Pair.rite', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=596,
)

_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='google.gink.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='google.gink.Entry.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='google.gink.Entry.behavior', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='google.gink.Entry.key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pair', full_name='google.gink.Entry.pair', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='span', full_name='google.gink.Entry.span', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='describing', full_name='google.gink.Entry.describing', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='google.gink.Entry.value', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='octets', full_name='google.gink.Entry.octets', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deletion', full_name='google.gink.Entry.deletion', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointee', full_name='google.gink.Entry.pointee', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='google.gink.Entry.expiry', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='effective', full_name='google.gink.Entry.effective', index=11,
      number=12, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='purge', full_name='google.gink.Entry.purge', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ENTRY_SPAN, _ENTRY_PAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='subject', full_name='google.gink.Entry.subject',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='contains', full_name='google.gink.Entry.contains',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=81,
  serialized_end=619,
)

_ENTRY_SPAN.containing_type = _ENTRY
_ENTRY_PAIR.fields_by_name['left'].message_type = muid__pb2._MUID
_ENTRY_PAIR.fields_by_name['rite'].message_type = muid__pb2._MUID
_ENTRY_PAIR.containing_type = _ENTRY
_ENTRY.fields_by_name['container'].message_type = muid__pb2._MUID
_ENTRY.fields_by_name['behavior'].enum_type = behavior__pb2._BEHAVIOR
_ENTRY.fields_by_name['key'].message_type = key__pb2._KEY
_ENTRY.fields_by_name['pair'].message_type = _ENTRY_PAIR
_ENTRY.fields_by_name['span'].message_type = _ENTRY_SPAN
_ENTRY.fields_by_name['describing'].message_type = muid__pb2._MUID
_ENTRY.fields_by_name['value'].message_type = value__pb2._VALUE
_ENTRY.fields_by_name['pointee'].message_type = muid__pb2._MUID
_ENTRY.oneofs_by_name['subject'].fields.append(
  _ENTRY.fields_by_name['key'])
_ENTRY.fields_by_name['key'].containing_oneof = _ENTRY.oneofs_by_name['subject']
_ENTRY.oneofs_by_name['subject'].fields.append(
  _ENTRY.fields_by_name['pair'])
_ENTRY.fields_by_name['pair'].containing_oneof = _ENTRY.oneofs_by_name['subject']
_ENTRY.oneofs_by_name['subject'].fields.append(
  _ENTRY.fields_by_name['span'])
_ENTRY.fields_by_name['span'].containing_oneof = _ENTRY.oneofs_by_name['subject']
_ENTRY.oneofs_by_name['subject'].fields.append(
  _ENTRY.fields_by_name['describing'])
_ENTRY.fields_by_name['describing'].containing_oneof = _ENTRY.oneofs_by_name['subject']
_ENTRY.oneofs_by_name['contains'].fields.append(
  _ENTRY.fields_by_name['value'])
_ENTRY.fields_by_name['value'].containing_oneof = _ENTRY.oneofs_by_name['contains']
_ENTRY.oneofs_by_name['contains'].fields.append(
  _ENTRY.fields_by_name['octets'])
_ENTRY.fields_by_name['octets'].containing_oneof = _ENTRY.oneofs_by_name['contains']
_ENTRY.oneofs_by_name['contains'].fields.append(
  _ENTRY.fields_by_name['deletion'])
_ENTRY.fields_by_name['deletion'].containing_oneof = _ENTRY.oneofs_by_name['contains']
_ENTRY.oneofs_by_name['contains'].fields.append(
  _ENTRY.fields_by_name['pointee'])
_ENTRY.fields_by_name['pointee'].containing_oneof = _ENTRY.oneofs_by_name['contains']
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {

  'Span' : _reflection.GeneratedProtocolMessageType('Span', (_message.Message,), {
    'DESCRIPTOR' : _ENTRY_SPAN,
    '__module__' : 'entry_pb2'
    # @@protoc_insertion_point(class_scope:google.gink.Entry.Span)
    })
  ,

  'Pair' : _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), {
    'DESCRIPTOR' : _ENTRY_PAIR,
    '__module__' : 'entry_pb2'
    # @@protoc_insertion_point(class_scope:google.gink.Entry.Pair)
    })
  ,
  'DESCRIPTOR' : _ENTRY,
  '__module__' : 'entry_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Entry)
  })
_sym_db.RegisterMessage(Entry)
_sym_db.RegisterMessage(Entry.Span)
_sym_db.RegisterMessage(Entry.Pair)


# @@protoc_insertion_point(module_scope)
