# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='key.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tkey.proto\x12\x0bgoogle.gink\"F\n\x03Key\x12\x10\n\x06number\x18\x01 \x01(\x12H\x00\x12\x10\n\x06octets\x18\x02 \x01(\x0cH\x00\x12\x14\n\ncharacters\x18\x03 \x01(\tH\x00\x42\x05\n\x03keyb\x06proto3'
)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='google.gink.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='google.gink.Key.number', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='octets', full_name='google.gink.Key.octets', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='characters', full_name='google.gink.Key.characters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key', full_name='google.gink.Key.key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=96,
)

_KEY.oneofs_by_name['key'].fields.append(
  _KEY.fields_by_name['number'])
_KEY.fields_by_name['number'].containing_oneof = _KEY.oneofs_by_name['key']
_KEY.oneofs_by_name['key'].fields.append(
  _KEY.fields_by_name['octets'])
_KEY.fields_by_name['octets'].containing_oneof = _KEY.oneofs_by_name['key']
_KEY.oneofs_by_name['key'].fields.append(
  _KEY.fields_by_name['characters'])
_KEY.fields_by_name['characters'].containing_oneof = _KEY.oneofs_by_name['key']
DESCRIPTOR.message_types_by_name['Key'] = _KEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'key_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Key)
  })
_sym_db.RegisterMessage(Key)


# @@protoc_insertion_point(module_scope)
