# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_file.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_file.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elog_file.proto\x12\x0bgoogle.gink\"\x9b\x01\n\x07LogFile\x12\x0f\n\x07\x63ommits\x18\x01 \x03(\x0c\x12\x36\n\rchain_entries\x18\x02 \x03(\x0b\x32\x1f.google.gink.LogFile.ChainEntry\x1aG\n\nChainEntry\x12\x11\n\tmedallion\x18\x01 \x01(\x04\x12\x13\n\x0b\x63hain_start\x18\x02 \x01(\x04\x12\x11\n\tchain_end\x18\x03 \x01(\x04\x62\x06proto3'
)




_LOGFILE_CHAINENTRY = _descriptor.Descriptor(
  name='ChainEntry',
  full_name='google.gink.LogFile.ChainEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='medallion', full_name='google.gink.LogFile.ChainEntry.medallion', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_start', full_name='google.gink.LogFile.ChainEntry.chain_start', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_end', full_name='google.gink.LogFile.ChainEntry.chain_end', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=187,
)

_LOGFILE = _descriptor.Descriptor(
  name='LogFile',
  full_name='google.gink.LogFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commits', full_name='google.gink.LogFile.commits', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_entries', full_name='google.gink.LogFile.chain_entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOGFILE_CHAINENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=187,
)

_LOGFILE_CHAINENTRY.containing_type = _LOGFILE
_LOGFILE.fields_by_name['chain_entries'].message_type = _LOGFILE_CHAINENTRY
DESCRIPTOR.message_types_by_name['LogFile'] = _LOGFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogFile = _reflection.GeneratedProtocolMessageType('LogFile', (_message.Message,), {

  'ChainEntry' : _reflection.GeneratedProtocolMessageType('ChainEntry', (_message.Message,), {
    'DESCRIPTOR' : _LOGFILE_CHAINENTRY,
    '__module__' : 'log_file_pb2'
    # @@protoc_insertion_point(class_scope:google.gink.LogFile.ChainEntry)
    })
  ,
  'DESCRIPTOR' : _LOGFILE,
  '__module__' : 'log_file_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.LogFile)
  })
_sym_db.RegisterMessage(LogFile)
_sym_db.RegisterMessage(LogFile.ChainEntry)


# @@protoc_insertion_point(module_scope)
