# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import muid_pb2 as muid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='movement.proto',
  package='google.gink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emovement.proto\x12\x0bgoogle.gink\x1a\nmuid.proto\"o\n\x08Movement\x12$\n\tcontainer\x18\x01 \x01(\x0b\x32\x11.google.gink.Muid\x12 \n\x05\x65ntry\x18\x02 \x01(\x0b\x32\x11.google.gink.Muid\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\x12\x12\r\n\x05purge\x18\x04 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[muid__pb2.DESCRIPTOR,])




_MOVEMENT = _descriptor.Descriptor(
  name='Movement',
  full_name='google.gink.Movement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='google.gink.Movement.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entry', full_name='google.gink.Movement.entry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dest', full_name='google.gink.Movement.dest', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='purge', full_name='google.gink.Movement.purge', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=154,
)

_MOVEMENT.fields_by_name['container'].message_type = muid__pb2._MUID
_MOVEMENT.fields_by_name['entry'].message_type = muid__pb2._MUID
DESCRIPTOR.message_types_by_name['Movement'] = _MOVEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Movement = _reflection.GeneratedProtocolMessageType('Movement', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENT,
  '__module__' : 'movement_pb2'
  # @@protoc_insertion_point(class_scope:google.gink.Movement)
  })
_sym_db.RegisterMessage(Movement)


# @@protoc_insertion_point(module_scope)
