name: Continuous Integration - Debian

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Build Debian Docker image with tests
      run: docker build . --platform=linux/amd64
