name: Continuous Integration

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: protobuf-compiler
          version: 1.0
    - name: Compile protos for the python implementation.
      run: make python/gink/builders
    - name: Build the python docker image.
      run: docker build ./python
    - name: Compile protos for the javascript implementation.
      run: make javascript/proto
    - name: Build the javascript docker image.
      run: docker build ./javascript
