name: Continuous Integration - MacOS

on: [push]

env:
  PYTHONPATH: /Users/runner/work/gink/gink/python

jobs:

  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./javascript

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@v1
    - name: Install protobuf-compiler
      run: echo $PWD && brew install protobuf && npm install -g protoc-gen-js
    - name: Compile protos and install packages for both implementations.
      run: cd .. && make
    - name: Run JS node-client test
      run: ./integration-tests/node-client-test.js
    - name: Run JS authentication test
      run: ./integration-tests/authentication-test.js
    - name: Run JS routing-server test
      run: ./integration-tests/routing-server-test.js
    - name: Run JS logbacked peers test
      run: ./integration-tests/logbacked-peers-test.js
    - name: Run JS unit tests
      run: npm run test
    - name: Run JS browser unit tests
      run: npm run browser-unit
    - name: Run JS browser integration tests
      run: npm run browser-integration
    - name: Update Version
      run: cd ../python && export VERSION=`date -u +0.%Y%m%d.%s` && sed -i "" "s/\${VERSION}/${VERSION}/g" setup.py
    - name: Install Python packages
      run: cd ../python && pip3 install .[test]
    - name: TypeScript-Python test
      run:  ./integration-tests/ts-py-test.js
    - name: Python-Python test
      run:  ./integration-tests/py-py-test.js
    - name: Python-TypeScript test
      run:  ./integration-tests/py-ts-test.js
