name: Publish to NPM
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Protobuf Compiler
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Build Protos
        run: cd .. && make javascript
      - name: Rebuild
        run: npm rebuild
      - name: Update Version
        run: export VERSION=`date -u +0.%Y%m%d.%s` && sed -i "s/\${VERSION}/${VERSION}/g" package.json
      - name: Publish package on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
