name: Publish Python distribution to PyPI

on:
  push:
    branches: [main]
    paths:
    - python/gink/__init__.py
    - python/gink/__main__.py
    - python/gink/impl/**
    - python/setup.py

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install Protobuf Compiler
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: protobuf-compiler
    - name: Update Version ENV
      run: |
        echo "GINK_VERSION=`date -u +0.%Y%m%d.%s`" >> "$GITHUB_ENV"
    - name: Build protos
      run: cd .. && make python/gink/builders
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: python/dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gink
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
